site_name: EdgeAIonPlatformse
site_url: https://alema416.github.io/EdgeAIonPlatforms/

theme:
  name: material
  font:
    text: Roboto       # body copy & headings
    code: Roboto Mono  # code blocks & inline code
plugins:
  - search
