site_name: EdgeAIonPlatforms
site_url: https://alema416.github.io/EdgeAIonPlatforms/

theme:
  name: material
  font:
    text: Roboto       # body copy & headings
    code: Roboto Mono  # code blocks & inline code
  palette:
    primary:
      main:    "#089484"
      light:   "#089484"
      dark:    "#089484"
    accent:
      main:    "#089484"

plugins:
  - search
